# Generated by Django 3.2.25 on 2025-10-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_users_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='emp_id',
        ),
    ]
