# Generated by Django 3.2.25 on 2025-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_remove_users_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Mobile_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
