# Generated by Django 3.2.25 on 2025-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_users_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company_mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
