# Generated by Django 3.2.25 on 2025-10-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20251002_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emp_designation',
            new_name='emp_role',
        ),
    ]
