# Generated by Django 3.2.25 on 2025-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_rename_emp_designation_users_emp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Mobile_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_bio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
