# Generated by Django 3.2.25 on 2025-10-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_auto_20251002_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Mobile_num',
            field=models.IntegerField(blank=True),
        ),
    ]
