# Generated by Django 3.2.25 on 2025-10-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_users_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Mobile_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
