# Generated by Django 3.2.25 on 2025-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_users_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Mobile_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
