# Generated by Django 3.2.25 on 2025-10-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20251002_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
