# Generated by Django 3.2.25 on 2025-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_alter_users_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserRole',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('hr', 'Recruiter')], max_length=10),
        ),
    ]
