# Generated by Django 3.2.25 on 2025-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_alter_users_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
