# Generated by Django 3.2.25 on 2025-10-20 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_users_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=15)),
                ('salary', models.IntegerField()),
                ('skills_required', models.TextField(help_text='Comma separated skills', max_length=200)),
                ('job_description', models.TextField(max_length=500)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
