# Generated by Django 3.2.25 on 2025-10-20 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_jobposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='last_date_to_apply',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobposts',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
