# Generated by Django 6.0 on 2025-12-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_auto_20251020_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposts',
            options={'ordering': ['-posted_on']},
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='skills_required',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
    ]
