# Generated by Django 6.0 on 2025-12-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_jobposts_options_alter_jobposts_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
