# Generated by Django 6.0 on 2025-12-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_jobposts_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposts',
            name='is_active',
        ),
    ]
