# Generated by Django 6.0 on 2025-12-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_remove_jobposts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='approval_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='registration_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
