# Generated by Django 6.0 on 2025-12-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_users_approval_email_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('required_skills', models.TextField()),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
