# Generated by Django 6.0 on 2025-12-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Mobile_num',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
