# Generated by Django 6.0 on 2026-02-21 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_job_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_num', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Enter a valid phone number.')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='O', max_length=1)),
                ('highest_degree', models.CharField(choices=[('high_school', 'High School Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('professional', 'Professional Degree'), ('other', 'Other')], max_length=20, verbose_name='Highest Qualification')),
                ('field', models.CharField(max_length=100, verbose_name='Field of Qualification')),
                ('graduation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year of Graduation')),
                ('institute', models.CharField(max_length=100, verbose_name='Institute Name')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Last Grade')),
                ('experience', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Work Experience')),
                ('exp_details', models.TextField(blank=True, null=True, verbose_name='Experience Details')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.DeleteModel(
            name='Job_Applications',
        ),
    ]
