# Generated by Django 6.0 on 2026-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_jobapplications_delete_job_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='jobapplications',
            constraint=models.UniqueConstraint(fields=('email', 'job'), name='unique_email_per_job'),
        ),
    ]
