# Generated by Django 6.0 on 2026-05-29 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_alter_jobapplications_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='applied_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
