# Generated by Django 6.0 on 2026-05-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0026_alter_jobapplications_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
