# Generated by Django 6.0 on 2026-05-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_alter_jobapplications_applied_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='Status',
            field=models.CharField(choices=[('Accpected', 'Accpected'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
