# Generated by Django 6.0 on 2026-06-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_job_responsibilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='jobposts',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
