# Generated by Django 6.0 on 2026-06-02 06:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_remove_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
