# Generated by Django 6.0 on 2026-06-02 07:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_alter_jobapplications_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
