# Generated by Django 5.2.15 on 2026-06-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_alter_jobapplications_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='approval_email_sent',
        ),
        migrations.RemoveField(
            model_name='users',
            name='emp_bio',
        ),
        migrations.RemoveField(
            model_name='users',
            name='emp_experience',
        ),
        migrations.RemoveField(
            model_name='users',
            name='emp_role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='emp_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='registration_email_sent',
        ),
    ]
